name: Backend CI

on:
  push:
    branches:
      - pre-commit-hooks
  pull_request:
    branches:
      - pre-commit-hooks

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Install MongoDB dependencies
        working-directory: .
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl3

            - name: Run Tests
        env:
          MONGOMS_VERSION: 7.0.14
        run: npm test